### ISSUE TITLE
Custom color theme for primary is not working properly

### ISSUE THREAD

**Issue by andreaseriksson** [praveenjuge/kutty#25]
Since upgrading to 0.4.0 and Tailwind 2 my custom color is not visible when doing a `btn btn-primary`

![image](https://user-images.githubusercontent.com/897748/100216840-10f04d00-2f13-11eb-923b-f9bb3d9e47dd.png)

However, it works when I **hover** the button:

![image](https://user-images.githubusercontent.com/897748/100216906-22d1f000-2f13-11eb-9fc4-f536470ef25e.png)

tailwind.config.js
```js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          light: "#5bc0be", // For lighter primary color
          default: "#3a506b", // Normal primary color
          dark: "#1c2541", // Used for hover, active, etc.
        },
      },
    },
  },
  plugins: [require("kutty")]
}
```

**Comment by praveenjuge** [comment]
I forgot to update this in the documentation, you have to change the `default` key to `DEFAULT` for it to work.

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          light: "#5bc0be", // For lighter primary color
          DEFAULT: "#3a506b", // Normal primary color
          dark: "#1c2541", // Used for hover, active, etc.
        },
      },
    },
  },
  plugins: [require("kutty")]
}
```

Sorry for the confusion!
