### ISSUE TITLE
Calling show on dialog from external component

### ISSUE THREAD

**Issue by weppami** [praveenjuge/kutty#3]
Hi, can you help with this :

I would like to call the dialog component from a livewire component that can pass value to alpine (i assume you're using it in your components), what is the value of x-data and x-show to use to trigger dialogs ?

Thanks and keep up the good work !!

**Comment by praveenjuge** [comment]
The current dialog component is written in vanilla js, but I am in the process of moving it to alpine. 

I'll let you know when it's done.

**Comment by praveenjuge** [comment]
Finally moved all the components to alpine,

The dialog has ` x-data="dialog()"` and x-show is done with `open: false`

Check out the examples in the documentation for more info: [https://kutty.netlify.app/docs/dialog/](https://kutty.netlify.app/docs/dialog/)
