### ISSUE TITLE
Open dialog creates scroll bar

### ISSUE THREAD

**Issue by Destaq** [praveenjuge/kutty#30]
For a page that does not have a scroll bar, everything gets shifted slightly to the left when the dialog opens, as a scrollbar is created.

**Before**
![image](https://user-images.githubusercontent.com/61620873/106596675-a7656e00-6555-11eb-892e-d37e7e49f1f9.png)

**After**
![image](https://user-images.githubusercontent.com/61620873/106596716-b3513000-6555-11eb-8649-11fafabb4e35.png)
Note the white bar on the far right.

Is there any way to prevent this behavior?

**Comment by Destaq** [comment]
Additionally, the dialog does not close when clicking on any of the buttons, just by clicking outside of it. I have AlpineJS as a `src` script, on the `@click="close"` event listeners, but the documentation did not show how to implement the *close* method.

**Comment by praveenjuge** [comment]
I'll fix the scroll bar bug 👍

Can you share a minimal reproduction repo for the close event not working?

**Comment by Destaq** [comment]
@praveenjuge Done.
https://github.com/Destaq/broken-kutty-dialog

1. `npm i`
2. `npm run build:css`
3. `npm run serve` = you can click outside the dialog to close it, but not on the buttons...

**Comment by Destaq** [comment]
This also seems to be the case for another dynamic component, the drawer @praveenjuge . If you look at the `drawer` branch on the repo, you can see that it does not work as well. No popup shows, the page only dims.

**Comment by praveenjuge** [comment]
Thanks, I'll take a look

**Comment by Destaq** [comment]
> Thanks, I'll take a look

Thank you, I hope it can be resolved.

I tried cloning this repo: https://github.com/praveenjuge/kutty/issues/5 that did not use AlpineJS, and the dialog worked perfectly. However, since then the dialog has been changed and no longer works - this may be useful information to you.

**Comment by Destaq** [comment]
@praveenjuge 
I've done some digging and solved the problem, there was a name clash.

Fixed in this PR: https://github.com/praveenjuge/kutty/pull/31

Although the dialog creating scrollbar to the right still happens.

**Comment by praveenjuge** [comment]
Hey, I have fixed the issue in the latest [commit](https://github.com/praveenjuge/kutty/commit/cef0730). 

You can check if it's working here: [https://codepen.io/praveenjuge/pen/KKNdavv](https://codepen.io/praveenjuge/pen/KKNdavv) 

I'll tag a release soon. Thanks for raising this issue!

**Comment by Destaq** [comment]
Works great, thanks for fixing and making Kutty!

**Comment by praveenjuge** [comment]
Fixed in release [0.5.0](https://github.com/praveenjuge/kutty/releases/tag/0.5.0)
