### ISSUE TITLE
Tooltips show up twice after some time

### ISSUE THREAD

**Issue by Destaq** [praveenjuge/kutty#32]
If you create a `tooltip` using Kutty, after a few seconds have passed, a tooltip will also show up using the default CSS pointer event.

This action cannot be overcome without also disabling Kutty tooltip (see [this StackOverflow post](https://stackoverflow.com/a/42671700/12876940)).

If you go to [Kutty Docs](https://kutty.netlify.app/docs/tooltip/) and hover over a tooltip for some time you can see it also shows up. Demonstrated in image below.

Ideal solution would be to use a different HTML element parameter than `title` for the `x-data` title, so that this "double tooltip title" error doesn't show up.

![image](https://user-images.githubusercontent.com/61620873/106787344-e37cf980-664f-11eb-863a-da0242d7c091.png)

**Comment by praveenjuge** [comment]
Good catch 👍

We should remove the native title attribute's content dynamically like how [bootstrap does](https://github.com/twbs/bootstrap/blob/main/js/src/tooltip.js#L610). So that we don't need to change the syntax. 

I'll do this with the next release!

**Comment by praveenjuge** [comment]
Fixed in release [0.5.0](https://github.com/praveenjuge/kutty/releases/tag/0.5.0)
