### ISSUE TITLE
Page with multiple dialogs

### ISSUE THREAD

**Issue by Destaq** [praveenjuge/kutty#33]
On my page, I have two separate dialogs that host different content.

When I trigger one of the dialogs, it can only be closed by clicking outside it (not on the X or close buttons implemented - it's a near-copy of the dialog in the docs). When I click on the other dialog, it can only be closed by clicking on the X or close button, not by clicking outside.

Is there any way to have multiple dialogs on the same page, or does the code need to be rewritten to have a dynamic dialog?

**Comment by praveenjuge** [comment]
I'll take a look

**Comment by praveenjuge** [comment]
Hey, I couldn't reproduce this, can you share some minimal code sample so I can see when this happens?
