### ISSUE TITLE
Can't click buttons in drawer on mobile Safari

### ISSUE THREAD

**Issue by thedaveesky** [praveenjuge/kutty#38]
Hello,
It is impossible to click save changes button in drawer opened in Safari browser on iOS. Buttons is hiding behind browser's UI and scrolling is impossible when drawer is opened. But when I can see the buttons, they are so low that I trigger browser UI instead of clicking on buttons.
This is a link to video presenting the issue: https://youtu.be/F8P2cbAt4xo

**Comment by praveenjuge** [comment]
I will check this soon 👍

**Comment by praveenjuge** [comment]
This is fixed in [v0.5.2](https://github.com/praveenjuge/kutty/releases/tag/v0.5.2) 👍
