### ISSUE TITLE
Cannot initialize dropdowns with Alpine

### ISSUE THREAD

**Issue by mcama** [praveenjuge/kutty#8]
Hi!

I'm currently using Kutty within a Nuxt app, but I cannot get the dropdowns to work ,since I'm getting `Uncaught ReferenceError: dropdown is not defined` on the JS console every time. Could it be something related to Alpine JS?

Thanks in advance and awesome job with Kutty!

**Comment by praveenjuge** [comment]
Hey, is kutty updated to the latest `0.2.0` version? 
And if that didn't work, did you properly register the plugin in Nuxt config? [example here](https://github.com/changjoo-park/issue-kutty-dialog/blob/20cbc14e065f78c7dd8b434a7e3d516ece320b20/nuxt.config.js#L38-L38)

**Comment by mcama** [comment]
Yes, kutty is on the latest version. Regarding the plugin, I'm registering the script (also Alpine) in `nuxt.config.js` file, like this:

```
export default {
        ...,
        script: [
            {
                src:
                    'https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.3.5/dist/alpine.min.js',
                body: true,
            },
            {
                src:
                    'https://cdn.jsdelivr.net/npm/kutty@latest/dist/kutty.min.js',
                body: true,
            },
        ],
        ...
}
```

**Comment by praveenjuge** [comment]
alpine is already bundled with the kutty js, maybe that's the problem, can you remove the alpine script there and check?

**Comment by mcama** [comment]
I removed de alpine script but the error still persist. This the full error:

```
Uncaught ReferenceError: dropdown is not defined
    at eval (eval at l (kutty.min.js:1), <anonymous>:3:36)
    at l (kutty.min.js:1)
    at new he (kutty.min.js:1)
    at Object.initializeComponent (kutty.min.js:1)
    at kutty.min.js:1
    at kutty.min.js:1
    at NodeList.forEach (<anonymous>)
    at Object.discoverComponents (kutty.min.js:1)
    at Object.start (kutty.min.js:1)
```
Other components the use JS, such as dialogs, are working like a charm.

**Comment by praveenjuge** [comment]
No idea what the error is, can you share full code in a minimal repo? It will help me identify why this error occurs

**Comment by mcama** [comment]
Hi. I've just created a minimal repo (where the issue can be reproduced) and added you as a collaborator.
Again, thank you for your help.

**Comment by mcama** [comment]
I confirm that setting the `mode` property to `'spa'` (instead of `mode: 'universal'`), in `nuxt.config.js`, solves the issue with dropdowns.
